// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parlivote.Core.Brokers.Storage;

#nullable disable

namespace Parlivote.Core.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20220409165411_SetMeetingIdInMotionNullOnDeleteMeeting")]
    partial class SetMeetingIdInMotionNullOnDeleteMeeting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Parlivote.Shared.Models.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Parlivote.Shared.Models.Motions.Motion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("Motions");
                });

            modelBuilder.Entity("Parlivote.Shared.Models.Motions.Motion", b =>
                {
                    b.HasOne("Parlivote.Shared.Models.Meetings.Meeting", "Meeting")
                        .WithMany("Motions")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Parlivote.Shared.Models.Meetings.Meeting", b =>
                {
                    b.Navigation("Motions");
                });
#pragma warning restore 612, 618
        }
    }
}
